# Generated by Django 5.0 on 2024-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymodel',
            old_name='sku',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='inventorymodel',
            name='product_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
