# Generated by Django 5.0 on 2024-06-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmodel',
            old_name='sku',
            new_name='product',
        ),
    ]
